# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.08.19
_src_path: gh:scientific-python/cookie
backend: hatch
email: rkansal@cern.ch
full_name: Raghav Kansal
license: MIT
org: LPC-HH
project_name: boostedhh
project_short_description: Common code for boosted HH analyses.
url: https://github.com/LPC-HH/boostedhh
vcs: false
